# These are supported funding model platforms

custom: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=RT3W8G98CETMS&source=url: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
